project:
  type: website
  output-dir: _site

website:
  title: "Antimicrobial PK/PD Workshop"
  navbar:
    title: "Antimicrobial PK/PD Workshop"
    left:
      - href: index.qmd
        text: Home
      - text: Sessions
        menu:
          - href: sessions/session_01/page.html
            text: Session 1
          - href: sessions/session_02/page.html
            text: Session 2
          - href: sessions/session_03/page.html
            text: Session 3
      - text: Info
        menu: 
          - href: info/agenda.qmd
            text: Agenda
          - href: info/team.qmd
            text: Team
          - href: info/support.qmd
            text: Support
          - href: info/faq.qmd
            text: Frequently Asked Questions
          - href: CONTRIBUTING.qmd
            text: Contributing
    right:
      - icon: github
        href: https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials
        target: _blank

freeze: auto

editor: visual

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    toc-location: left
    footer: '<a href="https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials" target="_blank">🔗 View on GitHub</a>'
    include-after-body: _includes/after-body.html
  clean-revealjs:
    theme: [default, _extensions/clean/clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    self-contained: false
    chalkboard:
      boardmarkerWidth: 3
      chalkWidth: 7
      boardColors: ["rgba(255,0,0,1)", "rgba(0,255,0,1)", "rgba(0,0,255,1)"]
      chalkColors: ["#FFFAAA", "#FFAAAA", "#AAAAFF"]
      toggleChalkboardButton: true
      toggleNotesButton: true
      navigation: true
      buttons: true
    footer: '<a href="https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials" target="_blank">🔗 View on GitHub</a>'
