project:
  type: default
  output-dir: .

format:
  clean-revealjs:
    theme: [default, _extensions/clean/clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    self-contained: false
    output-file: index.html
    chalkboard:
      boardmarkerWidth: 3
      chalkWidth: 7
      boardColors: ["rgba(255,0,0,1)", "rgba(0,255,0,1)", "rgba(0,0,255,1)"]
      chalkColors: ["#FFFAAA", "#FFAAAA", "#AAAAFF"]
      toggleChalkboardButton: true
      toggleNotesButton: true
      navigation: true
      buttons: true
    footer: '<a href="https://github.com/JacobKMcPherson/template_quarto_presentation" target="_blank">🔗 View on GitHub</a>'
