project:
  type: website
  output-dir: _site

website:
  title: "Antimicrobial PK/PD Workshop"
  navbar:
    title: "Antimicrobial PK/PD Workshop"
    left:
      - href: index.qmd
        icon: house
        text: Home
      - text: Sessions
        icon: graph-up
        menu:
          - href: pre-workshop-materials.qmd
            text: Pre-Workshop Materials
          - href: sessions/session_01/page.html
            text: Session 1
          - href: sessions/session_02/page.html
            text: Session 2
          - href: sessions/session_03/page.html
            text: Session 3
          - href: content/post-workshop-survey.qmd
            text: Post-Workshop Survey
      - text: Info
        icon: info-circle
        menu: 
          - href: info/team.qmd
            text: Team
          - href: info/support.qmd
            text: Support
          - href: info/faq.qmd
            text: Frequently Asked Questions
          - href: CONTRIBUTING.qmd
            text: Contributing
      - text: Resources
        icon: globe2
        menu: 
          - href: https://accesspharmacy.mhmedical.com/
            text: Access Pharmacy
          - href: https://www.boomer.org/
            text: David Bourne's Boomer Pharmacokinetics
          - href: https://www.certara.com/
            text: Certara
          - href: https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm
            text: Drugs@FDA
          - href: https://www.youtube.com/@NIHClinicalCenter
            text: NIH CC            
          - href: https://ncats.nih.gov/
            text: NCATS
          - href: https://iuphar.org/
            text: IUPHAR
          - href: https://www.icp.org.nz/
            text: Interactive Clinical Pharmacology
          - href: https://r-consortium.org/
            text: R Consortium "R Submissions" Working Group
          - href: https://pharmaverse.org/
            text: Pharmaverse
          - href: https://pharmar.org/
            text: PharmaR    
    right:
      - icon: github
        href: https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials
        target: _blank
  page-footer:
    left: "© 2025 Jacob K. McPherson"
    right: 
      - text: "License"
        href: LICENSE.html
      - text: "Contributors" 
        href: info/team.html

freeze: auto

editor: visual

pages:
  - SUPABASE_SETUP.md
  
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    toc-location: left
    include-after-body: _includes/after-body.html
  clean-revealjs:
    theme: [default, _extensions/clean/clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    self-contained: false
    chalkboard:
      boardmarkerWidth: 3
      chalkWidth: 7
      boardColors: ["rgba(255,0,0,1)", "rgba(0,255,0,1)", "rgba(0,0,255,1)"]
      chalkColors: ["#FFFAAA", "#FFAAAA", "#AAAAFF"]
      toggleChalkboardButton: true
      toggleNotesButton: true
      navigation: true
      buttons: true
    footer: '<a href="https://jacobkmcpherson.github.io/workshop_pkpd_antimicrobials" target="_blank">🔗 Return Home</a>'
