project:
  type: website
  output-dir: _site

website:
  title: "Antimicrobial PK/PD Workshop"
  navbar:
    title: "Antimicrobial PK/PD Workshop"
    left:
      - href: index.qmd
        icon: house
        text: Home
      - text: Sessions
        icon: graph-up
        menu:
          - href: sessions/session_01/page.html
            text: Session 1
          - href: sessions/session_02/page.html
            text: Session 2
          - href: sessions/session_03/page.html
            text: Session 3
      - text: Info
        icon: info-circle
        menu: 
          - href: info/team.qmd
            text: Team
          - href: info/support.qmd
            text: Support
          - href: info/faq.qmd
            text: Frequently Asked Questions
          - href: CONTRIBUTING.qmd
            text: Contributing
      - text: Resources
        icon: globe2
        menu: 
          - href: content/accesspharmacy.qmd
            text: Access Pharmacy
          - href: content/boomer.qmd
            text: Boomer
          - href: content/certara.qmd
            text: Certara
          - href: content/drugsatfda.qmd
            text: Drugs@FDA
          - href: content/nihcc.qmd
            text: NIH CC            
          - href: content/ncats.qmd
            text: NCATS
          - href: content/iuphar.qmd
            text: IUPHAR
          - href: content/icp.org.nz.qmd
            text: Interactive Clinical Pharmacology
          - href: content/rcrswg.qmd
            text: R Consortium "R Submissions" Working Group
          - href: content/pharmaverse.qmd
            text: Pharmaverse
          - href: content/pharmar.qmd
            text: PharmaR
            
    right:
      - icon: github
        href: https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials
        target: _blank

freeze: auto

editor: visual

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    toc-location: left
    footer: '<a href="https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials" target="_blank">🔗 View on GitHub</a>'
    include-after-body: _includes/after-body.html
  clean-revealjs:
    theme: [default, _extensions/clean/clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    self-contained: false
    chalkboard:
      boardmarkerWidth: 3
      chalkWidth: 7
      boardColors: ["rgba(255,0,0,1)", "rgba(0,255,0,1)", "rgba(0,0,255,1)"]
      chalkColors: ["#FFFAAA", "#FFAAAA", "#AAAAFF"]
      toggleChalkboardButton: true
      toggleNotesButton: true
      navigation: true
      buttons: true
    footer: '<a href="https://github.com/JacobKMcPherson/workshop_pkpd_antimicrobials" target="_blank">🔗 View on GitHub</a>'
